waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: 1
      position:
        x: -0.300725
        y: 6.811393
        z: -3
      euler_angles:
        x: 3.141593
        y: 3.141593
        z: -1.314843
      properties:
        - key: goal_radius
          value: 1.000000
        - key: stop
          value: false
      connections:
        - 2
    - id: registed_goal_4
      position:
        x: -27.66374
        y: -32.82571
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 3.079683
    - id: registed_goal_1
      position:
        x: -0.27491
        y: -18.93001
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.780379
    - id: registed_goal_2
      position:
        x: -2.648848
        y: -30.99604
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.533017
    - id: registed_goal_3
      position:
        x: -20.11524
        y: -32.84301
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.959788
