waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57
  waypoints:
    - id: 1
      position:
        x: -0.3800507
        y: -13.25647
        z: -2.999999
      euler_angles:
        x: -0
        y: -0
        z: 1.826749
      properties:
        - key: goal_radius
          value: 0.500000
        - key: stop
          value: false
      connections:
        - 2
